version: "3"
services:
  app:
    image: "garagestudi:v1.0"
    build:
      context: .
    ports:
      - 8000:8000
    environment:
      - PG_DB = garagevparrot_m 
      - PG_USER = garagevparrot_m
      - PG_PASSWORD = Okolo2023
      - PG_HOST = pj624348-001.eu.clouddb.ovh.net
      - PG_PORT = 35286
      - URL_SITE = https://garage-vparrot.fly.dev
      - JWTPRIVATEKEY = secretkey
      - SALT = 10