# fly.toml app configuration file generated for garage-vparrot on 2023-07-20T13:15:54+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "garage-vparrot"
primary_region = "cdg"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
